# Generated by Django 3.2.12 on 2022-03-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='score',
            new_name='days',
        ),
        migrations.AddField(
            model_name='record',
            name='basket_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
